### ISSUE TITLE
crawl_rotten_tomatoes() break down after search "史瑞克"

### ISSUE THREAD

**Issue by Error0229** [Error0229/Covie#2]
The error message as below.
```Using state Taipei City server backend.
Enter the movie name: 史瑞克
Traceback (most recent call last):
  File "D:\Covie\playground.py", line 7, in <module>
    result = Crawler.crawl()
  File "D:\Covie\src\MovieDataCrawler.py", line 56, in crawl
    self.crawl_rotten_tomatoes()
  File "D:\Covie\src\MovieDataCrawler.py", line 81, in crawl_rotten_tomatoes
    req = requests.get(movie_url, headers=headers).text
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
    self.crawl_rotten_tomatoes()
  File "D:\Covie\src\MovieDataCrawler.py", line 80, in crawl_rotten_tomatoes
    req = requests.get(movie_url, headers=headers).text
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/franchise/pokemon': No scheme supplied. Perhaps you meant http:///franchise/pokemon?```

**Comment by Vghxv** [comment]
modified line 89, change find to find_all
